/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CitiesResponseDto model module.
 * @module model/CitiesResponseDto
 * @version v1.0.0
 */
class CitiesResponseDto {
    /**
     * Constructs a new <code>CitiesResponseDto</code>.
     * @alias module:model/CitiesResponseDto
     */
    constructor() { 
        
        CitiesResponseDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CitiesResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CitiesResponseDto} obj Optional instance to populate.
     * @return {module:model/CitiesResponseDto} The populated <code>CitiesResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CitiesResponseDto();

            if (data.hasOwnProperty('cities')) {
                obj['cities'] = ApiClient.convertToType(data['cities'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CitiesResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CitiesResponseDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['cities'])) {
            throw new Error("Expected the field `cities` to be an array in the JSON data but got " + data['cities']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} cities
 */
CitiesResponseDto.prototype['cities'] = undefined;






export default CitiesResponseDto;

