/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerRegistrationRequestDto model module.
 * @module model/CustomerRegistrationRequestDto
 * @version v1.0.0
 */
class CustomerRegistrationRequestDto {
    /**
     * Constructs a new <code>CustomerRegistrationRequestDto</code>.
     * the customer&#39;s profile information
     * @alias module:model/CustomerRegistrationRequestDto
     * @param firstname {String} 
     * @param lastname {String} 
     * @param birthday {Date} 
     * @param city {String} 
     * @param streetAddress {String} 
     * @param postalCode {String} 
     */
    constructor(firstname, lastname, birthday, city, streetAddress, postalCode) { 
        
        CustomerRegistrationRequestDto.initialize(this, firstname, lastname, birthday, city, streetAddress, postalCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstname, lastname, birthday, city, streetAddress, postalCode) { 
        obj['firstname'] = firstname;
        obj['lastname'] = lastname;
        obj['birthday'] = birthday;
        obj['city'] = city;
        obj['streetAddress'] = streetAddress;
        obj['postalCode'] = postalCode;
    }

    /**
     * Constructs a <code>CustomerRegistrationRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerRegistrationRequestDto} obj Optional instance to populate.
     * @return {module:model/CustomerRegistrationRequestDto} The populated <code>CustomerRegistrationRequestDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerRegistrationRequestDto();

            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('birthday')) {
                obj['birthday'] = ApiClient.convertToType(data['birthday'], 'Date');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('streetAddress')) {
                obj['streetAddress'] = ApiClient.convertToType(data['streetAddress'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerRegistrationRequestDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerRegistrationRequestDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CustomerRegistrationRequestDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['firstname'] && !(typeof data['firstname'] === 'string' || data['firstname'] instanceof String)) {
            throw new Error("Expected the field `firstname` to be a primitive type in the JSON string but got " + data['firstname']);
        }
        // ensure the json data is a string
        if (data['lastname'] && !(typeof data['lastname'] === 'string' || data['lastname'] instanceof String)) {
            throw new Error("Expected the field `lastname` to be a primitive type in the JSON string but got " + data['lastname']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['streetAddress'] && !(typeof data['streetAddress'] === 'string' || data['streetAddress'] instanceof String)) {
            throw new Error("Expected the field `streetAddress` to be a primitive type in the JSON string but got " + data['streetAddress']);
        }
        // ensure the json data is a string
        if (data['postalCode'] && !(typeof data['postalCode'] === 'string' || data['postalCode'] instanceof String)) {
            throw new Error("Expected the field `postalCode` to be a primitive type in the JSON string but got " + data['postalCode']);
        }
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }

        return true;
    }


}

CustomerRegistrationRequestDto.RequiredProperties = ["firstname", "lastname", "birthday", "city", "streetAddress", "postalCode"];

/**
 * @member {String} firstname
 */
CustomerRegistrationRequestDto.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
CustomerRegistrationRequestDto.prototype['lastname'] = undefined;

/**
 * @member {Date} birthday
 */
CustomerRegistrationRequestDto.prototype['birthday'] = undefined;

/**
 * @member {String} city
 */
CustomerRegistrationRequestDto.prototype['city'] = undefined;

/**
 * @member {String} streetAddress
 */
CustomerRegistrationRequestDto.prototype['streetAddress'] = undefined;

/**
 * @member {String} postalCode
 */
CustomerRegistrationRequestDto.prototype['postalCode'] = undefined;

/**
 * @member {String} phoneNumber
 */
CustomerRegistrationRequestDto.prototype['phoneNumber'] = undefined;






export default CustomerRegistrationRequestDto;

