/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MoneyAmountDto from './MoneyAmountDto';

/**
 * The InsuranceQuoteDto model module.
 * @module model/InsuranceQuoteDto
 * @version v1.0.0
 */
class InsuranceQuoteDto {
    /**
     * Constructs a new <code>InsuranceQuoteDto</code>.
     * @alias module:model/InsuranceQuoteDto
     * @param expirationDate {Date} 
     * @param insurancePremium {module:model/MoneyAmountDto} 
     * @param policyLimit {module:model/MoneyAmountDto} 
     */
    constructor(expirationDate, insurancePremium, policyLimit) { 
        
        InsuranceQuoteDto.initialize(this, expirationDate, insurancePremium, policyLimit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, expirationDate, insurancePremium, policyLimit) { 
        obj['expirationDate'] = expirationDate;
        obj['insurancePremium'] = insurancePremium;
        obj['policyLimit'] = policyLimit;
    }

    /**
     * Constructs a <code>InsuranceQuoteDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsuranceQuoteDto} obj Optional instance to populate.
     * @return {module:model/InsuranceQuoteDto} The populated <code>InsuranceQuoteDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsuranceQuoteDto();

            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
            if (data.hasOwnProperty('insurancePremium')) {
                obj['insurancePremium'] = MoneyAmountDto.constructFromObject(data['insurancePremium']);
            }
            if (data.hasOwnProperty('policyLimit')) {
                obj['policyLimit'] = MoneyAmountDto.constructFromObject(data['policyLimit']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InsuranceQuoteDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InsuranceQuoteDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InsuranceQuoteDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `insurancePremium`
        if (data['insurancePremium']) { // data not null
          MoneyAmountDto.validateJSON(data['insurancePremium']);
        }
        // validate the optional field `policyLimit`
        if (data['policyLimit']) { // data not null
          MoneyAmountDto.validateJSON(data['policyLimit']);
        }

        return true;
    }


}

InsuranceQuoteDto.RequiredProperties = ["expirationDate", "insurancePremium", "policyLimit"];

/**
 * @member {Date} expirationDate
 */
InsuranceQuoteDto.prototype['expirationDate'] = undefined;

/**
 * @member {module:model/MoneyAmountDto} insurancePremium
 */
InsuranceQuoteDto.prototype['insurancePremium'] = undefined;

/**
 * @member {module:model/MoneyAmountDto} policyLimit
 */
InsuranceQuoteDto.prototype['policyLimit'] = undefined;






export default InsuranceQuoteDto;

