/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MoneyAmountDto from './MoneyAmountDto';

/**
 * The InsuranceQuoteResponseDto model module.
 * @module model/InsuranceQuoteResponseDto
 * @version v1.0.0
 */
class InsuranceQuoteResponseDto {
    /**
     * Constructs a new <code>InsuranceQuoteResponseDto</code>.
     * the response that contains the customer&#39;s decision whether to accept or reject an insurance quote
     * @alias module:model/InsuranceQuoteResponseDto
     * @param status {String} 
     */
    constructor(status) { 
        
        InsuranceQuoteResponseDto.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>InsuranceQuoteResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsuranceQuoteResponseDto} obj Optional instance to populate.
     * @return {module:model/InsuranceQuoteResponseDto} The populated <code>InsuranceQuoteResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsuranceQuoteResponseDto();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
            if (data.hasOwnProperty('insurancePremium')) {
                obj['insurancePremium'] = MoneyAmountDto.constructFromObject(data['insurancePremium']);
            }
            if (data.hasOwnProperty('policyLimit')) {
                obj['policyLimit'] = MoneyAmountDto.constructFromObject(data['policyLimit']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InsuranceQuoteResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InsuranceQuoteResponseDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InsuranceQuoteResponseDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // validate the optional field `insurancePremium`
        if (data['insurancePremium']) { // data not null
          MoneyAmountDto.validateJSON(data['insurancePremium']);
        }
        // validate the optional field `policyLimit`
        if (data['policyLimit']) { // data not null
          MoneyAmountDto.validateJSON(data['policyLimit']);
        }

        return true;
    }


}

InsuranceQuoteResponseDto.RequiredProperties = ["status"];

/**
 * @member {String} status
 */
InsuranceQuoteResponseDto.prototype['status'] = undefined;

/**
 * @member {Date} expirationDate
 */
InsuranceQuoteResponseDto.prototype['expirationDate'] = undefined;

/**
 * @member {module:model/MoneyAmountDto} insurancePremium
 */
InsuranceQuoteResponseDto.prototype['insurancePremium'] = undefined;

/**
 * @member {module:model/MoneyAmountDto} policyLimit
 */
InsuranceQuoteResponseDto.prototype['policyLimit'] = undefined;






export default InsuranceQuoteResponseDto;

