/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestStatusChangeDto model module.
 * @module model/RequestStatusChangeDto
 * @version v1.0.0
 */
class RequestStatusChangeDto {
    /**
     * Constructs a new <code>RequestStatusChangeDto</code>.
     * @alias module:model/RequestStatusChangeDto
     * @param status {String} 
     */
    constructor(status) { 
        
        RequestStatusChangeDto.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>RequestStatusChangeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestStatusChangeDto} obj Optional instance to populate.
     * @return {module:model/RequestStatusChangeDto} The populated <code>RequestStatusChangeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestStatusChangeDto();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RequestStatusChangeDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RequestStatusChangeDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RequestStatusChangeDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

RequestStatusChangeDto.RequiredProperties = ["status"];

/**
 * @member {Date} date
 */
RequestStatusChangeDto.prototype['date'] = undefined;

/**
 * @member {String} status
 */
RequestStatusChangeDto.prototype['status'] = undefined;






export default RequestStatusChangeDto;

