/**
 * Customer Management API
 * This API allows call center operators to interact with customers and to edit their user profiles.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerManagementApi);
  }
}(this, function(expect, CustomerManagementApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerManagementApi.InteractionEntity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InteractionEntity', function() {
    it('should create an instance of InteractionEntity', function() {
      // uncomment below and update the code to test InteractionEntity
      //var instance = new CustomerManagementApi.InteractionEntity();
      //expect(instance).to.be.a(CustomerManagementApi.InteractionEntity);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CustomerManagementApi.InteractionEntity();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new CustomerManagementApi.InteractionEntity();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new CustomerManagementApi.InteractionEntity();
      //expect(instance).to.be();
    });

    it('should have the property sentByOperator (base name: "sentByOperator")', function() {
      // uncomment below and update the code to test the property sentByOperator
      //var instance = new CustomerManagementApi.InteractionEntity();
      //expect(instance).to.be();
    });

  });

}));
