/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerSelfServiceApi);
  }
}(this, function(expect, CustomerSelfServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerSelfServiceApi.CitiesResponseDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CitiesResponseDto', function() {
    it('should create an instance of CitiesResponseDto', function() {
      // uncomment below and update the code to test CitiesResponseDto
      //var instance = new CustomerSelfServiceApi.CitiesResponseDto();
      //expect(instance).to.be.a(CustomerSelfServiceApi.CitiesResponseDto);
    });

    it('should have the property cities (base name: "cities")', function() {
      // uncomment below and update the code to test the property cities
      //var instance = new CustomerSelfServiceApi.CitiesResponseDto();
      //expect(instance).to.be();
    });

  });

}));
