/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerSelfServiceApi);
  }
}(this, function(expect, CustomerSelfServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomerRegistrationRequestDto', function() {
    it('should create an instance of CustomerRegistrationRequestDto', function() {
      // uncomment below and update the code to test CustomerRegistrationRequestDto
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be.a(CustomerSelfServiceApi.CustomerRegistrationRequestDto);
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property birthday (base name: "birthday")', function() {
      // uncomment below and update the code to test the property birthday
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "streetAddress")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postalCode")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new CustomerSelfServiceApi.CustomerRegistrationRequestDto();
      //expect(instance).to.be();
    });

  });

}));
