/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerSelfServiceApi);
  }
}(this, function(expect, CustomerSelfServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InsuranceQuoteRequestDto', function() {
    it('should create an instance of InsuranceQuoteRequestDto', function() {
      // uncomment below and update the code to test InsuranceQuoteRequestDto
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be.a(CustomerSelfServiceApi.InsuranceQuoteRequestDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property statusHistory (base name: "statusHistory")', function() {
      // uncomment below and update the code to test the property statusHistory
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property customerInfo (base name: "customerInfo")', function() {
      // uncomment below and update the code to test the property customerInfo
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property insuranceOptions (base name: "insuranceOptions")', function() {
      // uncomment below and update the code to test the property insuranceOptions
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property insuranceQuote (base name: "insuranceQuote")', function() {
      // uncomment below and update the code to test the property insuranceQuote
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property policyId (base name: "policyId")', function() {
      // uncomment below and update the code to test the property policyId
      //var instance = new CustomerSelfServiceApi.InsuranceQuoteRequestDto();
      //expect(instance).to.be();
    });

  });

}));
