/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerSelfServiceApi);
  }
}(this, function(expect, CustomerSelfServiceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerSelfServiceApi.Link();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Link', function() {
    it('should create an instance of Link', function() {
      // uncomment below and update the code to test Link
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be.a(CustomerSelfServiceApi.Link);
    });

    it('should have the property rel (base name: "rel")', function() {
      // uncomment below and update the code to test the property rel
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property href (base name: "href")', function() {
      // uncomment below and update the code to test the property href
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property hreflang (base name: "hreflang")', function() {
      // uncomment below and update the code to test the property hreflang
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property media (base name: "media")', function() {
      // uncomment below and update the code to test the property media
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property deprecation (base name: "deprecation")', function() {
      // uncomment below and update the code to test the property deprecation
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property profile (base name: "profile")', function() {
      // uncomment below and update the code to test the property profile
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CustomerSelfServiceApi.Link();
      //expect(instance).to.be();
    });

  });

}));
