/**
 * Customer Self-Service API
 * This API allows customers of Lakeside Mutual to sign up, log in and manage their policies and user profile themselves.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CitiesResponseDto from '../model/CitiesResponseDto';

/**
* CityReferenceDataHolder service.
* @module api/CityReferenceDataHolderApi
* @version v1.0.0
*/
export default class CityReferenceDataHolderApi {

    /**
    * Constructs a new CityReferenceDataHolderApi. 
    * @alias module:api/CityReferenceDataHolderApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCitiesForPostalCode operation.
     * @callback module:api/CityReferenceDataHolderApi~getCitiesForPostalCodeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CitiesResponseDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the cities for a particular postal code.
     * @param {String} postalCode the postal code
     * @param {module:api/CityReferenceDataHolderApi~getCitiesForPostalCodeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CitiesResponseDto}
     */
    getCitiesForPostalCode(postalCode, callback) {
      let postBody = null;
      // verify the required parameter 'postalCode' is set
      if (postalCode === undefined || postalCode === null) {
        throw new Error("Missing the required parameter 'postalCode' when calling getCitiesForPostalCode");
      }

      let pathParams = {
        'postalCode': postalCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = CitiesResponseDto;
      return this.apiClient.callApi(
        '/cities/{postalCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
